config/routes.rb
Rails.application.routes.draw do
  resources :users

 resources :games do
   resources :reviews
 end
 get '/home' => 'users#home'
 get '/collection' => 'games#collection'
 get '/login' => 'sessions#login'
 post '/login' => 'sessions#create'
 post '/logout' => 'sessions#destroy'

get '/reviewed_games' => 'users#reviewed_games'
 root 'welcome#home'

match 'auth/github/callback', to: 'sessions#create', via: [:get,:post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
#Get is used to fetch data and Post is used for submitting data

get 'auth/google_oauth2/callback', to: 'sessions#googleAuth', via: [:get, :post]
get 'auth/failure', to: redirect('/'), via: [:get, :post]
get 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews
  validates :name, :genre, :company, :platform, presence: true
  
  def self.most_recent(number)
    Game.all.order("created_at DESC").take(number)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates :content, presence: true

  def user_attributes=(user_attributes)
    user = User.find_by(name: user_attributes[:name])
    if !user
      user = User.create(name: user_attributes[:name], password: user_attributes[:password])
end
self.user = user
end
end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt
  has_many :games
  has_many :reviews
  has_many :reviewed_games, -> { distinct }, through: :reviews, source: :game, dependent: :destroy
  has_secure_password
  validates :name, :password, presence: true
  validates :email, uniqueness: true

def self.generic_password
  @password = BCrypt::Password.create(ENV['GENERIC_PASSWORD'])
end

def self.from_omniauth(auth)
  # Creates a new user only if it doesn't exist
  where(email: auth.info.email).first_or_initialize do |user|
    user.name = auth.info.name
    user.email = auth.info.email
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?, :user_not_authenticated?

    def current_user
        @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

    def logged_in?
        !!current_user
    end
    
    def user_not_authenticated?
        if !logged_in?
            redirect_to root_path
            return true
        end
        return false
    end
    
    def already_logged_in?
        if logged_in?
            redirect_to home_path(current_user)
            return true
        end
        return false
    end
    
    def to_user_not_authenticated?
        return if user_not_authenticated?
    end
    
    def to_already_logged_in?
        return if already_logged_in?
    end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :to_user_not_authenticated?, except: [:index, :show, :new]

    def new
        @game = Game.new
    end

    def create
        @game = current_user.games.build(game_params)
        if @game.valid? && @game.save
            redirect_to game_path(@game)
            #A "redirect_to" is used in your controller to reply to a request and it will simply redirect the request to a new URL.
            # it will redirect you to the new game that you had saved through the new url that was sent.
        else
            render :new
            #Render can be used in many ways but its mainly used to render your html views
            #it will render the "new" html view for games
        end
    end

    def index
        @games = Game.all
    end

    def show
        @game = Game.find(params[:id])
        @review_user = {}
        @game.reviews.each do |review|
            if @review_user[review.user_id] == nil
               user = User.find_by_id(review.user_id)
               @review_user[user.id] = user.name
            end
        end
    end

    def collection
        @Game = current_user.games.all
    end

    def edit
        @game = Game.find(params[:id])
        if @game.user != current_user
            redirect_to root_path
        end
    end

    def update
        @game = Game.find(params[:id])
        if @game.user == current_user && @game.valid? && @game.update(game_params)
            redirect_to game_path(@game)
        else
            render :edit
        end
    end

    def destroy
        @game = Game.find(params[:id])
        if @game.user_id == current_user.id
            @game.reviews.delete_all
        @game.delete
        redirect_to collection_path(@game.user)
        end
    end

    private
    def game_params
        params.require(:game).permit(:name, :genre, :company, :platform, :date, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @game = Game.find_by_id(params[:game_id])
    end

  def create
       # review = Review.create(review_params)
       @game = Game.find_by_id(params[:game_id])
        @review = @game.reviews.create(review_params)
       redirect_to game_path(@game) #need to redirect to show
   end

  def edit
    @review = Review.find_by_id(params[:id])
    if 
    @review.user != current_user
    redirect_to review.game(user.id)
  end
end

  def index
    @game = Game.find_by_id(params[:game_id])
  end

   private
   def review_params
       params.require(:review).permit(:content, :user_id, :game_id, user_attributes:[:name, :password, :password_confirmation])
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 


def login
    already_logged_in?
    @user = User.new
end

def create
  @user = User.find_by(name: params[:user][:name])
  if @user && @user.authenticate(params[:user][:password])
    session[:user_id] = @user.id
    redirect_to home_path(@user)
  else
    render :login
  end
end

   def googleAuth
    #get access tokens from the google server
    access_token = request.env["omniauth.auth"]
    user = User.from_omniauth(access_token)
    user.password = User.generic_password
    #login(user)
    # Access_token is used to authenticate request made from the rails application to the google server
    #user.google_token = access_token.credentials.token
    #refresh_token to request new access_token
    #Note: Refresh_token is only sent once during the first request
    #refresh_token = access_token.credentials.refresh_token
    #user.google_refresh_token = refresh_token if refresh_token.present?
    if user.save
    session[:user_id] = user.id
    redirect_to home_path(user)
    else
      render :new
   end
  end 

   def auth
    request.env["omniauth.auth"]
   end

def destroy
  session[:user_id] = nil
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :to_already_logged_in?, except: [:home, :reviewed_games]

def new
  @user = User.new
end

def create
  @user = User.new user_params
  if @user.valid? && @user.save
    session[:user_id] = @user.id
    redirect_to home_path(@user)
  else
    render :new
  end
end

def home
  user_not_authenticated?
  current_user
end

def reviewed_games
  @user = current_user
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
end
end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    #Checks if logged_in already, redirects to users home if so
       def home
           already_logged_in?
       end
   end
   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def recent_games
    recent_games = Game.most_recent(3)
    game_user = {}
    recent_games.each do |game|
      if game_user[game.user_id] == nil
        user = User.find_by_id(game.user_id)
        game_user[user.id] = user.name
      end
    end

    game_list = []
    recent_games.each do |game|
      if game.id != nil
        game_list << "#{game.name}, owned by #{game_user[game.user_id]}"
      end
    end
    return game_list
end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<% if @game.errors.any? %>
        <div id= "error_explanation" >
            <h2>
            <%= pluralize(@game.errors.count, "error") %>
            prohibited this game from being created:
            </h2>

            <ul>
            <% @game.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
        <% end %>
        <br/>



<%= form_for @game do |f| %>
    <%= f.hidden_field :user_id %>    
    <%= f.label 'Name:' %><br>
    <%= f.text_field :name %><br>
<br>
    <%= f.label 'Genre:' %><br>
    <%= f.text_area :genre %><br>
<br>
    <%= f.label 'Company:' %><br>
    <%= f.text_area :company %><br>
<br>
    <%= f.label 'Platform:' %><br>
    <%= f.text_area :platform %><br>
<br>
    <%= f.label 'Release Date' %><br>
    <%= f.text_field :date %><br>
<br>
    <%= f.submit %>
<% end %>

app/views/games/collection.html.erb
<h1><%= @user.name %>'s Collection </h1>

<%= link_to 'Home', home_path(@user) %><br>



<h3>Here is a list of the games in your collection:</h3>
<ul>
    <% @user.games.each do |game| %>
        <li>
            <%= link_to game.name, game_path(game) %>
        </li>
    <% end %>
</ul>

app/views/games/edit.html.erb
<h2> Edit your game: </h2>
<%= link_to 'Home', home_path(@user) %>
<br>
<br>

<%= render 'form' %>

app/views/games/index.html.erb
<% if current_user %>
<h2> Hello <%= current_user.name %>, take a look at all of our other collector's games!</h2>

<%= link_to 'Home', home_path %>

<% else %>

    <h2> You must log in to see other users collections! </h2>
    <h2> If you do not have an account: </h2> 
        <%= link_to 'click here to register!', new_user_path %>

    <% end %>
<br>
<br>
<% counter = 1 %>
<% @games.each do |game| %>
<h3> <%= counter %> . </h3>
    <h4>Name: <%= game.name %> </h4>
    <h4>Genre: <%= game.genre %> </h4>
    <h4>Company: <%= game.company %> </h4>
    <h4>Platform: <%= game.platform %> </h4>
    <h4>Date: <%= game.date %> </h4>
    <%= link_to 'Review on this ' + game.name, game_path(game)%>
    <% counter += 1 %>
<% end %>
<br/>
<br>

app/views/games/new.html.erb
<h2> That is a great new addition! </h2>

<%= link_to 'Home', home_path(@user) %>
<br>
<br>

<%= render 'form' %>

app/views/games/show.html.erb
<h2> Viewing <%= @game.name %> </h2>
<p>
    <h3>Found by: <%= @game.user.name %></h3>
    <h3>Genre: <%= @game.genre %></h3>
    <h3>Company: <%= @game.company %></h3>
    <h3>System: <%= @game.platform %></h3>
    <h3>Date: <%= @game.date %></h3>
</p>
<%if current_user && current_user.id == @game.user.id %>
     <%= link_to 'Edit this game!', edit_game_path(@game)%><br>
     <br>
     <%= link_to 'Delete this Game!', game_path(@game), method: :delete, data: {confirm: 'Are you sure you would like to delete this entry?'}%><br>
     <br>
     <%= link_to 'See the reviews of this Game!', "/games/#{params[:id]}/reviews" %>
<% end %>
<br>
<br>
    <%= link_to 'Home', home_path(@user) %>
<br>
<br>


<h3>Reviews:</h3>
    <% @game.reviews.each do |review| %>
        <%if review.id != nil %>
            <%=@review_user[review.user_id]%> said,
            "<%= review.content %>"<br>
            <br>
        <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h3>Reviews:</h3>
    <% @game.reviews.each do |review| %>
        <%if review.id != nil %>
            <%=@review_user[review.user_id]%> said,
            "<%= review.content %>"<br>
            <br>
        <% end %>
        <% end %>

<%= link_to 'Write a new review', new_game_review_path(@game) %>

app/views/reviews/new.html.erb
<%= form_for @game.reviews.build, :as => :review, :url => game_reviews_path(@game) do |f| %>
    <%= f.hidden_field :game_id %>

    <% if current_user %>
        <%= f.hidden_field :user_id, value: current_user.id %>
    <% else %>

    <h3> Sign up as a Collector to review this game! </h3>

        <%= f.fields_for :user, User.new do |user_fields| %>
            <%= user_fields.label :name, 'Name:' %>
            <%= user_fields.text_field :name %>
            <%= user_fields.label :password, 'Password:' %>
            <%= user_fields.password_field :password %>
            <%= user_fields.label :password_confirmation, 'Password Confirmation:' %>
            <%= user_fields.password_field :password_confirmation %>
        <% end %>
    <% end %>

<h3>Leave a review on this game:</h3>

<p>
    <%= f.label :content, "New Review" %>:
    <%= f.text_area :content %>
</p>

<%= f.submit %>

<% end %><br>


<h3>Reviews:</h3>
<% @game.reviews.each do |review| %>
    <%if review.id != nil %>
        <%=@review_user[review.user_id]%> said,
        "<%= review.content %>"<br>
        <br>
    <% end %>
<% end %>

app/views/users/home.html.erb
<h1> Hey player, <%= @user.name %></h1>

<h2> Take a look at your:</h2>
<%= link_to 'Collection', collection_path(@user)%>


<h2> Add a new game to your collection: </h2>
<%= link_to 'New Game', new_game_path(@user) %><br>

<h2> View all other member's collection: </h2>
<%= link_to 'All Games', games_path(@user) %><br>

<h2>These are the games you have reviewed on:</h2>
    <%= link_to 'Reviews', reviewed_games_path %><br>
    <br>
    <br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
    <input type = submit value = 'Log Out'>
<% end %>

app/views/users/new.html.erb
<h1>Please Sign up below!</h1>

<% if @user.errors.any? %>
<div id= "error_explanation" >
<h2>
  <%= pluralize(@user.errors.count, "error") %>
  prohibited this user from being created:
</h2>

<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

<%= form_for @user do |f| %>
  
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.label :email %>
<%= f.email_field :email %>
<br>
<%= f.submit "Sign Up!" %>
<% end %>

app/views/users/reviewed_games.erb
<h1> Hey player, <%= @user.name %></h1>

<br>
    <%= link_to 'Home', home_path(@user) %>
<br>

<h3>Here are all the games you have reviewed:</h3>

    <% @user.reviewed_games.each do |game| %>
        <%if game.id != nil %>
            <%= link_to 'You have reviewed ' + game.name, game_path(game)%>
            <br>
        <% end %>
<% end %>

app/views/welcome/home.html.erb
<h1> Welcome to Game Collector </h1>


<div style="font-size: 25px; font-weight: semibold;">Welcome! Game Collector was built so you can share all of your experiences
  of all the games you have played in the present and past! Share your experiences with other players in our welcoming community! Happy gaming! </div>

<br>
    <h3> Latest Collection Submissions: </h3>

    <% recent_games.each do |recent_game| %>
        <%= recent_game %><br/>
    <% end %>

<br>

<h3><%= link_to 'Check out all of our members games!', games_path %><br></h3>

<br>


<h3> Sign Up with the link below </h3>
<%= link_to(controller: 'users', action: 'new') { 'Sign Up' } %>
<h3> Log In with the link below </h3>
<%= link_to(controller: 'sessions', action: 'login') { 'Log In' } %>
<br>

<%= link_to('Log in with Google!', '/auth/google_oauth2', id: "sign_in") %>
 